FROM node:20
WORKDIR /app/server
COPY package.json .
COPY *.js .
EXPOSE 8080
RUN npm install
ENV MONGO="true" \
    REDIS_URL="redis://redis:6379" \
    MONGO_URL="mongodb://mongodb:27017/users"
CMD ["node", "server.js"]